DELETE FROM SUPERHERO;
INSERT INTO SUPERHERO (ID, NAME, FULLNAME, PLACE_OF_BIRTH) VALUES (1L, 'Superman', 'Clark Joseph Kent', 'Metropolis');
INSERT INTO SUPERHERO (ID, NAME, FULLNAME, PLACE_OF_BIRTH) VALUES (2L, 'Batman', 'Bruce Wayne', 'Ciudad Gotica');
INSERT INTO SUPERHERO (ID, NAME, FULLNAME, PLACE_OF_BIRTH) VALUES (3L, 'Thor','Thor Odinson', 'Asgard');
